export const RECEIVE_BANNERS = 'receive_banners'    // 轮播图
export const RECEIVE_NAVIGATION_HISTORY = 'receive_navigation_history'    // 浏览历史
export const RECEIVE_USERINFO = 'receive_userinfo'          // 登录成功获取用户数据
export const RECEIVE_USER_LEVEL = 'receive_user_level'                  // 获取用户等级
export const RECEIVE_MUSIC_CATEGORY = 'receive_music_category'          // 获取音乐种类
export const RECEIVE_HOT_MUSIC_CATEGORY = 'receive_hot_music_category'  // 获取热门歌曲种类
export const RECEIVE_CURRENT_MUSIC_TAG = 'receive_current_music_tag'    // 接收当前选中的音乐种类
export const RESET_USERINFO = 'reset_userinfo'                          // 退出登录
export const RECEIVE_USER_PLAYLIST = 'receive_user_playlist'            // 获取用户歌单名称
export const RECEIVE_SHOW_PLAYLIST = 'receive_show_playlist'            // 歌单区域现实的歌单
export const RECEIVE_ALL_BOARD_LIST = 'receive_all_board_list'          // 获取全部榜单数据
export const RECEIVE_SONG_LIST_DETAIL = 'receive_song_list_detail'      // 获取歌单详情数据
export const RECEIVE_SONG_LIST_COMMENT = 'receive_song_list_comment'    // 获取歌单评论详情
export const RESET_SOMETHING = 'reset_something'                        // 重置state的部分信息 评论/歌单...
export const RECEIVE_SEND_COMMENT = 'receive_send_comment'                        // 接收评论 添加/删除
export const RECEIVE_NEW_MUSIC = 'receive_new_music'                    // 获取新歌
export const RECEIVE_MUSIC_URL = 'receive_music_url'                    // 接收音乐 url
export const RECEIVE_MUSIC_PLAY_LIST = 'receive_music_play_list'        // 接收音乐播放列表
export const RECEIVE_SONG_LYRIC = 'receive_music_lyric'                 // 获取音乐歌词
